<?php
/**
 * Created by PhpStorm.
 * User: vyfvfv
 * Date: 04.06.15
 * Time: 12:54
 */

namespace QSoft\Foundation\Component\Router;

use FastRoute\Dispatcher\GroupCountBased;
use QSoft\Foundation\Component\AjaxLoader;

class Dispatcher extends GroupCountBased {

    public function dispatch($httpMethod, $uri)
    {
        if ((new AjaxLoader())->isValidAjaxRequest()) {
            $httpMethod .= '@ajax';
        }

        if (SITE_DIR !== '/') {
            $uri = substr_replace($uri, '', 0, strlen(SITE_DIR)-1);
        }

        return parent::dispatch($httpMethod, $uri); // TODO: Change the autogenerated stub
    }
}
